---
- name: Installing system packages...
  become: true
  apt:
    update_cache: true
    name:
      - postgresql
      - postgresql-contrib

- name: Enabling service...
  become: true
  service:
    name: postgresql
    enabled: true
