- name: Installing zsh packages...
  become: true
  become_user: root
  apt:
    name:
      - zsh
      - zsh-syntax-highlighting

- name: Execute shell installation script
  shell:
    chdir: /tmp
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install zsh-plugins
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "~{{ target_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master
