---
- name: Installs and configures PostgreSQL
  hosts: localhost
  become: true
  tasks:
    - name: Installing system packages...
      apt:
        update_cache: true
        name:
          - postgresql
          - postgresql-contrib
      notify: psql_version

    - name: Enabling service...
      service:
        name: postgresql
        enabled: true

  handlers:
    - name: Printing version...
      listen: psql_version
      command: psql --version
      changed_when: false
