---
- name: 'Makes sure user "{{ target_user }}" exists'
  user:
    name: "{{ target_user }}"
    groups: sudo
    append: true
    comment: Daze User
    shell: "/usr/bin/zsh"

- name: 'Creates user "{{ target_user }}" home directories'
  file:
    path: "~{{ target_user }}/{{ item }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    state: directory
    mode: 0755
  loop:
    - ".local/bin"

- name: Creating sudoer file in /etc/sudoers.d/
  copy:
    dest: "/etc/sudoers.d/{{ target_user }}"
    content: "{{ target_user }} ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    validate: "visudo -cf %s"
    mode: 0640

- name: Installing SSH Public keys to target user...
  loop: "{{ ssh_public_keys }}"
  loop_control:
    loop_var: ssh_public_key
  authorized_key:
    user: "{{ target_user }}"
    key: "{{ ssh_public_key }}"
