---
name: Ansible codebase
on:
  push:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yml"
env:
  registry: 169567906943.dkr.ecr.eu-central-1.amazonaws.com
  app: ansible

jobs:
  build:
    name: Build Ansible image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        if: steps.check-cache-image.outputs.cache-hit != 'true'
        uses: actions/checkout@v3

      - name: Cache image
        uses: actions/cache@v3
        id: check-cache-image
        with:
          path: ansible.tar
          key: ${{ runner.os }}-build-${{ hashFiles('ansible/**') }}

      - name: Building docker image...
        if: steps.check-cache-image.outputs.cache-hit != 'true'
        working-directory: ./ansible
        run: docker build . -t ${{ env.registry }}/${{ github.repository }}/${{ env.app }}:dev

      - name: Save image to tar
        if: steps.check-cache-image.outputs.cache-hit != 'true'
        run: docker save ${{ env.registry }}/${{ github.repository }}/${{ env.app }}:dev -o ansible.tar

      - name: Cache image
        if: steps.check-cache-image.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: make-cache-image
        with:
          path: ansible.tar
          key: ${{ runner.os }}-build-${{ hashFiles('ansible/**') }}

  test:
    name: Test Ansible playbook
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Get cached image
        uses: actions/cache@v3
        id: cache-image
        with:
          path: ansible.tar
          key: ${{ runner.os }}-build-${{ hashFiles('ansible/**') }}

      - name: Load Docker image
        run: docker load --input ansible.tar

      - name: Installing packages...
        run: sudo apt-get -qq install openssh-server -y

      - name: Creating temporary SSH key...
        run: |
          mkdir $HOME/.ssh/
          ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N "" -C "temp key"
          cat "$HOME/.ssh/id_rsa.pub" > $HOME/.ssh/authorized_keys

      - name: Running Ansible container...
        run: docker run -e CI --rm -v $HOME/.ssh/id_rsa:/etc/ansible/ssh.pem ${{ env.registry }}/${{ github.repository }}/${{ env.app }}:dev -u $USER -vvv

  push:
    needs: test
    name: Push to Registry
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    steps:
      - name: Get cached image
        uses: actions/cache@v3
        id: cache-image
        with:
          path: ansible.tar
          key: ${{ runner.os }}-build-${{ hashFiles('ansible/**') }}

      - name: Load Docker image
        run: docker load --input ansible.tar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::169567906943:role/allow-auto-deploy-from-other-accounts
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push images to Github Registry
        run: docker push ${{ env.registry }}/${{ github.repository }}/${{ env.app }}:dev
