---
name: Ansible codebase
on:
  push:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yml"
env:
  registry: ghcr.io
  app: ansible

jobs:
  build:
    name: Build Ansible image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    # outputs:
    #   cache-hit: ${{ steps.cache-image.outputs.cache-hit }}
    steps:
      - name: Cache image
        uses: actions/cache@v3
        id: check-cache-image
        with:
          path: ansible.tar
          key: ${{ runner.os }}-build-${{ hashFiles('ansible/**') }}

      - name: Check out repository code
        if: steps.check-cache-image.outputs.cache-hit != 'true'
        uses: actions/checkout@v3

      - name: Building docker image...
        if: steps.check-cache-image.outputs.cache-hit != 'true'
        working-directory: ./ansible
        run: docker build . -t ${{ env.registry }}/${{ github.repository }}/${{ env.app }}:dev

      - name: Save image to tar
        if: steps.check-cache-image.outputs.cache-hit != 'true'
        run: docker save ${{ env.registry }}/${{ github.repository }}/${{ env.app }}:dev -o ansible.tar

      - name: Cache image
        if: steps.check-cache-image.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: make-cache-image
        with:
          path: ansible.tar
          key: ${{ runner.os }}-build-${{ hashFiles('ansible/**') }}

  test:
    name: Test Ansible playbook
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Get cached image
        uses: actions/cache@v3
        id: cache-image
        with:
          path: ansible.tar
          key: ${{ runner.os }}-build-${{ hashFiles('ansible/Dockerfile') }}

      - name: Load Docker image
        run: docker load --input ansible.tar

      - name: Installing packages...
        run: sudo apt-get -qq install openssh-server -y

      - name: Creating temporary SSH key...
        run: |
          mkdir $HOME/.ssh/
          ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N "" -C "temp key"
          cat "$HOME/.ssh/id_rsa.pub" > $HOME/.ssh/authorized_keys

      - name: Running Ansible container...
        run: docker run -e CI --rm -v $HOME/.ssh/id_rsa:/etc/ansible/ssh.pem ${{ env.registry }}/${{ github.repository }}/${{ env.app }}:dev -u $USER -vvv

  push:
    needs: test
    name: Push to ghcr.io
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    steps:
      - name: Get cached image
        uses: actions/cache@v3
        id: cache-image
        with:
          path: ansible.tar
          key: ${{ runner.os }}-build-${{ hashFiles('ansible/Dockerfile') }}

      - name: Load Docker image
        run: docker load --input ansible.tar

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images to Github Registry
        run: docker push ${{ env.registry }}/${{ github.repository }}/${{ env.app }}:dev
